### ISSUE TITLE
I tried to train system but get error

### ISSUE THREAD

**Issue by rnunziata** [jcwleo/random-network-distillation-pytorch#28]
When I try to train system from start by removing the pretrained models it complains that it can not find the models.

```
python train.py
{'OPTIONS': {'envtype': '[atari, mario]', 'trainmethod': 'RND', 'envid': 'MontezumaRevengeNoFrameskip-v4', 'maxstepperepisode': '4500', 'extcoef': '2.', 'learningrate': '1e-4', 'numenv': '2', 'numstep': '128', 'gamma': '0.999', 'intgamma': '0.99', 'lambda': '0.95', 'stableeps': '1e-8', 'statestacksize': '4', 'preprocheight': '84', 'proprocwidth': '84', 'usegae': 'True', 'usegpu': 'True', 'usenorm': 'False', 'usenoisynet': 'False', 'clipgradnorm': '0.5', 'entropy': '0.001', 'epoch': '4', 'minibatch': '4', 'ppoeps': '0.1', 'intcoef': '1.', 'stickyaction': 'True', 'actionprob': '0.25', 'updateproportion': '0.25', 'lifedone': 'False', 'obsnormstep': '50'}}
load model...
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main()
  File "train.py", line 100, in main
    agent.model.load_state_dict(torch.load(model_path))
  File "/home/rjn/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/MontezumaRevengeNoFrameskip-v4.model'
```

**Comment by rnunziata** [comment]
Apparently it does not check to see if file exist by uses a hard coded flag to load it or not.
    is_load_model = False
